### ISSUE TITLE
Why not to join with lenadroid/awesome-oss-mentors

### ISSUE THREAD

**Issue by andy-shev** [IIIT-Delhi/awesome-mentors#1]
lenadroid/awesome-oss-mentors provides a good wide list of mentors already. Why to create another splited one?

**Comment by sedflix** [comment]
This is meant for use within our college. It's kind of a way to know who(in the college) works on what and is willing to mentor others in that area. Repo name is misleading I guess.

**Comment by andy-shev** [comment]
The repository name a bit confusing then :-) 
You also can consider branching, right? Name your college as a branch?

**Comment by sedflix** [comment]
After careful consideration of your suggestions, I think we are going to skip it. A few of us were not comfortable with "Name your college as a branch". 
The confusing regarding repo name wouldn't occur now. 

And thanks a ton for your suggestions :D
