### ISSUE TITLE
Need help with contribution to Debian

### ISSUE THREAD

**Issue by jnoni** [IIIT-Delhi/awesome-mentors#5]
Hi there.

[This](https://www.outreachy.org/2018-may-august/communities/debian/) is the project to which I will be applying to for the summer internship. Can anyone please help me with my first contribution, if you've got some knowledge/experience with Debian packaging skills? Or if not you, then maybe a friend of yours who might have missed this post?

My email ID: rupal15081@iiitd.ac.in

**Comment by jnoni** [comment]
@lionaneesh 
@PalashBansal96 
@peey 
@darkryder 
@geekSiddharth 
@naman 
Any pointers?

**Comment by naman** [comment]
Hey @Rupal-IIITD! 
Good to see that you're going to apply for Debian. I can see that there are two projects on the page you have mentioned. Have you chosen any of them yet?

**Comment by jnoni** [comment]
@naman

The project within Debian that I want to apply to is "Quality assurance for biological applications inside Debian". Mainly because I have a background and interest in Computational Biology and luckily I could resonate with this project due to the CB part. The other component of it (and the most important and major one, on which all implementations will be based) is Debian packaging. And this is kinda kept as pre-requisite for the applicants.

I have started looking at some resources on Google for it to get a gist of it, but I still feel that to actual get into coding it up, I'll need someone's mentoring. 

Well, I think this hurdle and hesitation is partly due to my first encounter with Open source. And to not make it feel anymore alien to me, I thought to ask here for help.

**Comment by sedflix** [comment]
I guess the session by ILUG-D on Debian Packing in our college was a bit too late.
